# Generated by Django 5.2.1 on 2025-06-15 13:43

import django.db.models.deletion
import notes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('any_academic', models.CharField(default=notes.models.default_any_academic, max_length=20)),
                ('grau', models.CharField(choices=[('ASIX', 'ASIX'), ('DAM', 'DAM'), ('DAW', 'DAW')], max_length=50)),
                ('nivell', models.CharField(choices=[('1r', 'Primer'), ('2n', 'Segon')], max_length=10)),
            ],
            options={
                'unique_together': {('any_academic', 'grau', 'nivell')},
            },
        ),
        migrations.CreateModel(
            name='Assignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nom_curt', models.CharField(default=' ', max_length=5)),
                ('grup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignatures', to='notes.grup')),
            ],
        ),
        migrations.CreateModel(
            name='Alumne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('cognoms', models.CharField(max_length=150)),
                ('grup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumnes_curs', to='notes.grup')),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.alumne')),
                ('assignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.assignatura')),
            ],
            options={
                'unique_together': {('alumne', 'assignatura')},
            },
        ),
        migrations.AddField(
            model_name='alumne',
            name='assignatures',
            field=models.ManyToManyField(related_name='alumnes_assignatura', through='notes.Matricula', to='notes.assignatura'),
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('matricula', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes_matricula', to='notes.matricula')),
            ],
            options={
                'unique_together': {('matricula',)},
            },
        ),
    ]
